version: '3.8'

services:
  server:
    build: ./server
    container_name: django-server
    ports:
      - "8000:8000"
    volumes:
      - ./charts:/app
    depends_on:
      - db

  client:
    build: ./client
    container_name: nextjs-client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    depends_on:
      - server

  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
